using UnityEngine;

public class TitleArrow : MonoBehaviour
{
    RectTransform rectTransform;    // Panelڈم‚جچہ•W

    // ‘I‘ًژˆ‚جˆê——
    enum Choice
    {
        Start,
        Continue,
        Credit,
        Exit,
        Max,
    }
    Choice choice;

    // –îˆَ‚جچہ•Wƒfپ[ƒ^
    float[,] position = new float[4, 2] {
        { 136,   96 },
        { 136,   44 },
        { 178,  -54 },
        { 230, -162 }
    };

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        choice = Choice.Start;  // ڈ‰ٹْڈَ‘ش‚حڈ‰‚ك‚©‚ç
        rectTransform = GetComponent<RectTransform>();
        rectTransform.anchoredPosition = new Vector2(position[0, 0], position[0, 1]);
    }

    // Update is called once per frame
    void Update()
    {
        // ƒQپ[ƒ€ƒpƒbƒh“ü—حژو“¾
        float move = Input.GetAxis("Stick_Y") + Input.GetAxis("Cross_Y");

        // –îˆَ
        if (Input.GetKeyDown(KeyCode.UpArrow) || move > 0.0f)   // ڈم
        {
            choice -= 1; if (choice < Choice.Start) { choice = Choice.Exit; }
        }
        if (Input.GetKeyDown(KeyCode.DownArrow) || move < 0.0f) // ‰؛
        {
            choice += 1; if (choice > Choice.Exit) { choice = Choice.Start; }
        }
        rectTransform.anchoredPosition =
            new Vector2(position[(int)choice, 0], position[((int)choice), 1]);  // Œ»چف‘I‘ً‚µ‚ؤ‚¢‚é‚ئ‚±‚ë‚ةˆع“®

        // ƒVپ[ƒ“‘Jˆع
        if (Input.GetKeyUp(KeyCode.Return) || Input.GetButtonDown("Decide"))
        {
            switch (choice)
            {
                case Choice.Start:      // چإڈ‰‚©‚ç
                    SceneLoader.Instance.LoadScene(SceneName.Select, true, 2.0f);
                    //AudioManager.Instance.StopBGM(1f);
                    break;
                case Choice.Continue:   // “r’†‚©‚ç
                    SceneLoader.Instance.LoadScene(SceneName.Select, true, 2.0f);
                    //AudioManager.Instance.StopBGM(1f);
                    break;
                case Choice.Credit:     // —ک—p‹K–ٌ—ق
                    Debug.Log("ƒNƒŒƒWƒbƒg");
                    break;
                case Choice.Exit:       // ڈI—¹
                    Debug.Log("ƒQپ[ƒ€ڈI—¹");
#if UNITY_EDITOR
                    UnityEditor.EditorApplication.isPlaying = false;
#endif
                    break;
                case Choice.Max:
                    break;
            }
        }
    }
}
